package tienda_virtual;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;



public class Frm_Registro_Clientes extends javax.swing.JFrame {
    Connection con=null;
    Statement stmt=null;
    
    public Frm_Registro_Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
        public static String wIdCliente="";
        public static String wNombre="";
        public static String wpApellido="";
        public static String wsApellido="";
        public static String wFechaNac="";
        public static String wCorreo="";
        public static String wDireccion="";       
        public static String wDisPostal="";      
        public static String wMunicipio="";      
        public static String wProvincia="";
        public static String wTelefono="";
        public static String wMujer="";
        public static String wHombre="";
          public static String  wNomBanco="";     
          public static String  wBicBanco="";    
          public static String  wCodCliente="";
          public static String  wIbanClie="";      
          public static String  wFecCaducidad="";      
          public static String  wGenero="";
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGenero = new javax.swing.ButtonGroup();
        jtpDatosBancarios = new javax.swing.JTabbedPane();
        jtapDatCliente = new javax.swing.JPanel();
        jibNombre = new javax.swing.JLabel();
        jlbFechaNac = new javax.swing.JLabel();
        jtapDatCliente1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlbDirec = new javax.swing.JLabel();
        jlbMunic = new javax.swing.JLabel();
        jlbProv = new javax.swing.JLabel();
        jtfDireccion = new javax.swing.JTextField();
        jtfMunicipio = new javax.swing.JTextField();
        jtfProvincia = new javax.swing.JTextField();
        jlbDPostal = new javax.swing.JLabel();
        jtfDisPostal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlbPrimerApellidp = new javax.swing.JLabel();
        jlbCorreoE = new javax.swing.JLabel();
        jlbTelefono = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfPrimeroApellido = new javax.swing.JTextField();
        jtfCorreoE = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfFechaNac = new javax.swing.JTextField();
        jplMujerHombre = new javax.swing.JPanel();
        jrbHombre = new javax.swing.JRadioButton();
        jrbMujer = new javax.swing.JRadioButton();
        jlbSegundoApellido = new javax.swing.JLabel();
        jtfSegundoApellido = new javax.swing.JTextField();
        jbtCancelClie = new javax.swing.JButton();
        jbtGrabarClie = new javax.swing.JButton();
        jbtSalirClie = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtapDatosBanco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodCliente = new javax.swing.JTextField();
        jtfBicBanco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfNomBanco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfIbanClie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfFecCaducidad = new javax.swing.JTextField();
        jbtSalirBanco = new javax.swing.JButton();
        jbtCancelBanc = new javax.swing.JButton();
        jbtGrabarBanc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Registro Clientes");

        jtpDatosBancarios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtpDatosBancarios.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jtpDatosBancarios.setName("jtpaRegistro"); // NOI18N

        jibNombre.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jibNombre.setText("Nombre...:");

        jlbFechaNac.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jlbFechaNac.setText("Fecha Nacimiento...:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jlbDirec.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jlbDirec.setText("Dirección...:");

        jlbMunic.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jlbMunic.setText("Municipio..:");

        jlbProv.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jlbProv.setText("Provicia...:");

        jtfDireccion.setText(" ");
        jtfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDireccionActionPerformed(evt);
            }
        });
        jtfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDireccionKeyTyped(evt);
            }
        });

        jtfMunicipio.setText(" ");
        jtfMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMunicipioActionPerformed(evt);
            }
        });
        jtfMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMunicipioKeyTyped(evt);
            }
        });

        jtfProvincia.setText(" ");
        jtfProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProvinciaActionPerformed(evt);
            }
        });
        jtfProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfProvinciaKeyTyped(evt);
            }
        });

        jlbDPostal.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jlbDPostal.setText("Dtro. Postal ...:");

        jtfDisPostal.setText(" ");
        jtfDisPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDisPostalActionPerformed(evt);
            }
        });
        jtfDisPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDisPostalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMunic)
                    .addComponent(jlbProv))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfProvincia)
                    .addComponent(jtfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jlbDPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfDisPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDirec)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMunic)
                    .addComponent(jtfMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbProv)
                    .addComponent(jtfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDPostal)
                    .addComponent(jtfDisPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jlbPrimerApellidp.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jlbPrimerApellidp.setText("Prim. Apellido");

        jlbCorreoE.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jlbCorreoE.setText("Correo Eléctonico...:");

        jlbTelefono.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jlbTelefono.setText("Teléfono...:");

        jtfNombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfNombre.setToolTipText("Introduce tu nombre");
        jtfNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jtfPrimeroApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrimeroApellidoActionPerformed(evt);
            }
        });
        jtfPrimeroApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrimeroApellidoKeyTyped(evt);
            }
        });

        jtfCorreoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCorreoEActionPerformed(evt);
            }
        });
        jtfCorreoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCorreoEKeyTyped(evt);
            }
        });

        jtfTelefono.setText(" ");
        jtfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoActionPerformed(evt);
            }
        });
        jtfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTelefonoKeyTyped(evt);
            }
        });

        jtfFechaNac.setText("dd/mm/aaaa");
        jtfFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFechaNacActionPerformed(evt);
            }
        });
        jtfFechaNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFechaNacKeyTyped(evt);
            }
        });

        jplMujerHombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bgGenero.add(jrbHombre);
        jrbHombre.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jrbHombre.setText("Hombre");
        jrbHombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbHombreItemStateChanged(evt);
            }
        });

        bgGenero.add(jrbMujer);
        jrbMujer.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jrbMujer.setText("Mujer");
        jrbMujer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbMujerItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jplMujerHombreLayout = new javax.swing.GroupLayout(jplMujerHombre);
        jplMujerHombre.setLayout(jplMujerHombreLayout);
        jplMujerHombreLayout.setHorizontalGroup(
            jplMujerHombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplMujerHombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplMujerHombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplMujerHombreLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jrbHombre))
                    .addComponent(jrbMujer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jplMujerHombreLayout.setVerticalGroup(
            jplMujerHombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplMujerHombreLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jrbMujer)
                .addGap(18, 18, 18)
                .addComponent(jrbHombre)
                .addContainerGap())
        );

        jlbSegundoApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbSegundoApellido.setText("Seg. Apellido");

        jtfSegundoApellido.setText("jTextField1");
        jtfSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSegundoApellidoActionPerformed(evt);
            }
        });
        jtfSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSegundoApellidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbPrimerApellidp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfPrimeroApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jlbSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfSegundoApellido))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jtfFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbCorreoE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jplMujerHombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(176, 176, 176))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPrimeroApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbPrimerApellidp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbSegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addComponent(jtfSegundoApellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCorreoE)
                            .addComponent(jtfCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbTelefono)))
                    .addComponent(jplMujerHombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jbtCancelClie.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jbtCancelClie.setText("Cancelar");
        jbtCancelClie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), null, null));
        jbtCancelClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelClieActionPerformed(evt);
            }
        });

        jbtGrabarClie.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jbtGrabarClie.setText("Grabar");
        jbtGrabarClie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), null, null));
        jbtGrabarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGrabarClieActionPerformed(evt);
            }
        });

        jbtSalirClie.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jbtSalirClie.setText("Salir");
        jbtSalirClie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), null, null));
        jbtSalirClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirClieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtapDatCliente1Layout = new javax.swing.GroupLayout(jtapDatCliente1);
        jtapDatCliente1.setLayout(jtapDatCliente1Layout);
        jtapDatCliente1Layout.setHorizontalGroup(
            jtapDatCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtapDatCliente1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jtapDatCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jtapDatCliente1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jbtSalirClie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtCancelClie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jbtGrabarClie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jtapDatCliente1Layout.setVerticalGroup(
            jtapDatCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtapDatCliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jtapDatCliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtCancelClie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalirClie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtGrabarClie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel7.setText("Fecha Nacimiento...:");

        javax.swing.GroupLayout jtapDatClienteLayout = new javax.swing.GroupLayout(jtapDatCliente);
        jtapDatCliente.setLayout(jtapDatClienteLayout);
        jtapDatClienteLayout.setHorizontalGroup(
            jtapDatClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtapDatClienteLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jtapDatClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbFechaNac)
                    .addComponent(jibNombre))
                .addContainerGap(602, Short.MAX_VALUE))
            .addGroup(jtapDatClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jtapDatCliente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jtapDatClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jtapDatClienteLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(697, Short.MAX_VALUE)))
        );
        jtapDatClienteLayout.setVerticalGroup(
            jtapDatClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtapDatClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jibNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jlbFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(jtapDatClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jtapDatClienteLayout.createSequentialGroup()
                    .addComponent(jtapDatCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jtapDatClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jtapDatClienteLayout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(362, Short.MAX_VALUE)))
        );

        jtpDatosBancarios.addTab("Datos Cliente", jtapDatCliente);

        jtapDatosBanco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel1.setText("Código Cliente");

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel2.setText("BIC ...:");

        jtfCodCliente.setText(" ");
        jtfCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodClienteActionPerformed(evt);
            }
        });
        jtfCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCodClienteKeyTyped(evt);
            }
        });

        jtfBicBanco.setText("jTextField2");
        jtfBicBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBicBancoActionPerformed(evt);
            }
        });
        jtfBicBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBicBancoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel10.setText("BANCO");

        jtfNomBanco.setText("jTextField3");
        jtfNomBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomBancoActionPerformed(evt);
            }
        });
        jtfNomBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNomBancoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel11.setText("IBAN CLIENTE ..:");

        jtfIbanClie.setText("jTextField4");
        jtfIbanClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIbanClieActionPerformed(evt);
            }
        });
        jtfIbanClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIbanClieKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jLabel12.setText("Fecha Caducidad ...: ");

        jtfFecCaducidad.setText("jTextField5");
        jtfFecCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFecCaducidadActionPerformed(evt);
            }
        });
        jtfFecCaducidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFecCaducidadKeyTyped(evt);
            }
        });

        jbtSalirBanco.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jbtSalirBanco.setText("Salir");
        jbtSalirBanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), null, null));
        jbtSalirBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirBancoActionPerformed(evt);
            }
        });

        jbtCancelBanc.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jbtCancelBanc.setText("Cancelar");
        jbtCancelBanc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), null, null));
        jbtCancelBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelBancActionPerformed(evt);
            }
        });

        jbtGrabarBanc.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        jbtGrabarBanc.setText("Grabar");
        jbtGrabarBanc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153), null, null));
        jbtGrabarBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGrabarBancActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jtapDatosBancoLayout = new javax.swing.GroupLayout(jtapDatosBanco);
        jtapDatosBanco.setLayout(jtapDatosBancoLayout);
        jtapDatosBancoLayout.setHorizontalGroup(
            jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtapDatosBancoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jtapDatosBancoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jtfIbanClie)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtapDatosBancoLayout.createSequentialGroup()
                        .addComponent(jbtSalirBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtCancelBanc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jtapDatosBancoLayout.createSequentialGroup()
                        .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jtapDatosBancoLayout.createSequentialGroup()
                                .addComponent(jtfBicBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(jLabel10)))))
                .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtapDatosBancoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jtfFecCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jtapDatosBancoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jbtGrabarBanc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jtapDatosBancoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jtfNomBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jtapDatosBancoLayout.setVerticalGroup(
            jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtapDatosBancoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBicBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtfNomBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfIbanClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtfFecCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addGroup(jtapDatosBancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSalirBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCancelBanc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtGrabarBanc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jtpDatosBancarios.addTab("Datos Bancarios", jtapDatosBanco);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpDatosBancarios, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpDatosBancarios)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTONES DE CANCELAR Y GRABAR CLIENTE.
    
    private void jbtCancelClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelClieActionPerformed
        
        jtfPrimeroApellido.setText("");
        jtfSegundoApellido.setText("");
        jtfNombre.setText("");
        jtfCorreoE.setText("");
        jtfDireccion.setText("");
        jtfDisPostal.setText("");
        jtfFechaNac.setText("");
        jtfMunicipio.setText("");
        jtfProvincia.setText("");
        jtfTelefono.setText("");
        //bgGenero.setText("");
        jrbHombre.setText("");
        jrbMujer.setText("");

    }//GEN-LAST:event_jbtCancelClieActionPerformed

    private void jbtGrabarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGrabarClieActionPerformed
        if(jtfNombre.getText().equals("")
         ||(jtfPrimeroApellido.getText().equals(""))
         || (jtfSegundoApellido.getText().equals(""))
         ||(jtfDireccion.getText().equals("")))
                
            
    {javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos\n","Aviso!",
     javax.swing.JOptionPane.INFORMATION_MESSAGE);
    jtfNombre.requestFocus();
            
            String nom    =   jtfNombre.getText();
            String pap    =   jtfPrimeroApellido.getText();
            String sap    =   jtfSegundoApellido.getText(); 
            String fnac   =   jtfFechaNac.getText();
            String correoe=   jtfCorreoE.getText();
            String dir    =   jtfDireccion.getText();
            int post      =   Integer.parseInt(jtfDisPostal.getText());
            String mun    =   jtfMunicipio.getText();
            String priv   =   jtfProvincia.getText();
            int telef     =   Integer.parseInt(jtfTelefono.getText());
            String M      =   jrbMujer.getText();
            String H      =   jrbHombre.getText();
           
           
        }
        else{
        
               
           }
           
 //comprobar si la casilla esta vacia y sacar ventana emergente informativa.
            
            
            if(jtfNombre !=null){
                wNombre=jtfNombre.getText();
                System.out.println(wNombre);
            }else{
                JOptionPane.showMessageDialog(null, "Nombre del cliente  es obligatorio");
                System.out.println("Esta vacio");
            }
            
            if(jtfPrimeroApellido !=null){
                wpApellido=jtfPrimeroApellido.getText();
                System.out.println(wpApellido);
            }else{
                JOptionPane.showMessageDialog(null, "Apellido del  cliente es obligatorio");
                System.out.println("Esta vacio");
            }
   
            if(jtfSegundoApellido !=null){
                wsApellido=jtfSegundoApellido.getText();
                System.out.println(wsApellido);
            }else{
                JOptionPane.showMessageDialog(null, "Apellido del  cliente es obligatorio");
                System.out.println("Esta vacio");
            }
          
            if(jtfCorreoE !=null){
                wCorreo=jtfCorreoE.getText();
                System.out.println(wCorreo);
            }else{
                JOptionPane.showMessageDialog(null, "Correo del  cliente  es obligatorio");
                System.out.println("Esta vacio");
            }
       
            if(jtfDireccion !=null){
                wDireccion=jtfDireccion.getText();
                System.out.println(wDireccion);
            }else{
                JOptionPane.showMessageDialog(null, "Direccion del  cliente es obligatorio");
                System.out.println("Esta vacio");
            }
          
            if(jtfDisPostal !=null){
                wDisPostal=jtfDisPostal.getText();
                System.out.println(wDisPostal);
            }else{
                JOptionPane.showMessageDialog(null, "Postal del cliente es obligatorio");
                System.out.println("Esta vacio");
            }
       
            if(jtfFechaNac !=null){
                wFechaNac=jtfFechaNac.getText();
                System.out.println(wFechaNac);
            }else{
                JOptionPane.showMessageDialog(null, "Fecha de nacimiento del  cliente es obligatoria");
                System.out.println("Esta vacio");
            }
      
            if(jtfMunicipio !=null){
                wMunicipio=jtfMunicipio.getText();
                System.out.println(wMunicipio);
            }else{
                JOptionPane.showMessageDialog(null, "Municipio del cliente obligatorio");
                System.out.println("Esta vacio");
            }
       
            if(jtfProvincia !=null){
                wProvincia=jtfProvincia.getText();
                System.out.println(wProvincia);
            }else{
                JOptionPane.showMessageDialog(null, "Provincia del cliente es obligatorio");
                System.out.println("Esta vacio");
            }
       
            if(jtfTelefono !=null){
                wTelefono=jtfTelefono.getText();
                System.out.println(wTelefono);
            }else{
                JOptionPane.showMessageDialog(null, "Numero de telefono del  cliente es obligatorio");
                System.out.println("Esta vacio");
            }
    }//GEN-LAST:event_jbtGrabarClieActionPerformed

    //BOTONES DE GRABAR Y CANCELAR DATOS DE BANCO.
    
    
    private void jbtGrabarBancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGrabarBancActionPerformed
     
      if(jtfBicBanco.getText().equals("")
         ||(jtfIbanClie.getText().equals("")))
        
                
            
    {javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos\n","Aviso!",
     javax.swing.JOptionPane.INFORMATION_MESSAGE);
    jtfBicBanco.requestFocus();
            
        
        
        int bic       =  Integer.parseInt(jtfBicBanco.getText());
        String nomB   =  jtfNomBanco.getText();
        Float iban    =  Float.valueOf(jtfIbanClie.getText());
        String fcad   =  jtfFecCaducidad.getText();
        
        
    }else
      //Conectarse a la bd y hacer un INSERT 
          
     
         if(jtfNomBanco !=null){
                wNomBanco=jtfNomBanco.getText();
                
            }else{
                JOptionPane.showMessageDialog(null, "Nombre del banco no   es obligatorio");
                System.out.println("Esta vacio");
            }
         
       
         if(jtfBicBanco !=null){
                wBicBanco=jtfBicBanco.getText();
              
            }else{
                JOptionPane.showMessageDialog(null, "BIC  es obligatorio");
                System.out.println("Esta vacio");
            }
         
        
                 if(jtfCodCliente !=null){
                wCodCliente=jtfCodCliente.getText();
               
            }else{
                JOptionPane.showMessageDialog(null, "Nombre del cliente  es obligatorio");
                System.out.println("Esta vacio");
            }
         
       
         if(jtfFecCaducidad !=null){
                wFecCaducidad=jtfFecCaducidad.getText();
               
            }else{
                JOptionPane.showMessageDialog(null, "No  es obligatorio");
                System.out.println("Esta vacio");
            }
         
  
         if(jtfIbanClie !=null){
                wIbanClie=jtfIbanClie.getText();
               
            }else{
                JOptionPane.showMessageDialog(null, "Es obligatorio");
                System.out.println("Esta vacio");
         }
         
    
    }//GEN-LAST:event_jbtGrabarBancActionPerformed

    private void jbtCancelBancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelBancActionPerformed
       jtfBicBanco.setText("");
       jtfCodCliente.setText("");
       jtfFecCaducidad.setText("");
       jtfIbanClie.setText("");
       jtfNomBanco.setText("");        
    }//GEN-LAST:event_jbtCancelBancActionPerformed

    
    //DATOS DEL CLIENTE.
    
    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
       jtfNombre.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Nombre 
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String Nombre=JOptionPane.showInputDialog("Introduce tu nombre");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+Nombre);//se hace para comprobar.
        jtfNombre.setText(Nombre);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        //wNombre=jtfNombre.getText();
       //System.out.println(wNombre);//para comprobar.
         
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfPrimeroApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrimeroApellidoActionPerformed
      
        jtfPrimeroApellido.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Apellidos
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String pApellido=JOptionPane.showInputDialog("Introduce tu primer apellido");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+pApellido);//se hace para comprobar.
        jtfPrimeroApellido.setText(pApellido);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wpApellido=jtfPrimeroApellido.getText();
       System.out.println(wpApellido);//para comprobar.
           
    }//GEN-LAST:event_jtfPrimeroApellidoActionPerformed

    private void jtfFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaNacActionPerformed
        
         jtfFechaNac.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al da intro en la casilla Fecha de NAcimiento 
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String FechaN=JOptionPane.showInputDialog("Introduce tu fecha de nacimiento en formato dd/MM/AA");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+FechaN);//se hace para comprobar.
        jtfFechaNac.setText(FechaN);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wFechaNac=jtfFechaNac.getText();
       System.out.println(wFechaNac);//para comprobar.
         // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaNacActionPerformed

    private void jtfCorreoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCorreoEActionPerformed
         jtfCorreoE.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al da intro en la casilla Correo
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String correos =JOptionPane.showInputDialog("Introduce tu correo  ");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+correos);//se hace para comprobar.
        jtfCorreoE.setText(correos);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wCorreo=jtfCorreoE.getText();
       System.out.println(wCorreo);//para comprobar.
          // TODO add your handling code here:
    }//GEN-LAST:event_jtfCorreoEActionPerformed

    private void jtfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoActionPerformed
      
         jtfTelefono.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al da intro en la casilla TElefono 
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String telef=JOptionPane.showInputDialog("Introduce tu telefono");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+telef);//se hace para comprobar.
        jtfTelefono.setText(telef);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wTelefono=jtfTelefono.getText();
       System.out.println(wTelefono);//para comprobar.
            // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefonoActionPerformed

    private void jtfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDireccionActionPerformed
         jtfDireccion.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Direccion 
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String direc=JOptionPane.showInputDialog("Introduce tu direccion actual");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+direc);//se hace para comprobar.
        jtfDireccion.setText(direc);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wDireccion=jtfDireccion.getText();
       System.out.println(wDireccion);//para comprobar.
        
    }//GEN-LAST:event_jtfDireccionActionPerformed

    private void jtfMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMunicipioActionPerformed
         
         jtfMunicipio.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Municipio 
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String municip=JOptionPane.showInputDialog("Introduce nombre de tu municipio ");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+municip);//se hace para comprobar.
        jtfMunicipio.setText(municip);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wMunicipio=jtfMunicipio.getText();
       System.out.println(wMunicipio);//para comprobar.
       
    }//GEN-LAST:event_jtfMunicipioActionPerformed

    private void jtfProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProvinciaActionPerformed
         jtfProvincia.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Provincia 
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String provinc=JOptionPane.showInputDialog("Introduce tu nombre");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+provinc);//se hace para comprobar.
        jtfProvincia.setText(provinc);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wProvincia=jtfProvincia.getText();
       System.out.println(wProvincia);//para comprobar.
      
    }//GEN-LAST:event_jtfProvinciaActionPerformed

    private void jtfDisPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDisPostalActionPerformed
      
         jtfDisPostal.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla  DisPostal
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String postal=JOptionPane.showInputDialog("Introduce tu codigo postal");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+postal);//se hace para comprobar.
        jtfDisPostal.setText(postal);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wDisPostal=jtfDisPostal.getText();
       System.out.println(wDisPostal);//para comprobar.
            
    }//GEN-LAST:event_jtfDisPostalActionPerformed

    //BOTONES SALIRcliente Y SALIRdatosBanco
    
    private void jbtSalirClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirClieActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtSalirClieActionPerformed

    private void jbtSalirBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirBancoActionPerformed
       this.dispose();  
    }//GEN-LAST:event_jbtSalirBancoActionPerformed

    private void jtfSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSegundoApellidoActionPerformed
        jtfSegundoApellido.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Apellidos
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String sApellido=JOptionPane.showInputDialog("Introduce tu segundo apellido");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+sApellido);//se hace para comprobar.
        jtfSegundoApellido.setText(sApellido);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wsApellido=jtfSegundoApellido.getText();
       System.out.println(wsApellido);//para comprobar.  
    }//GEN-LAST:event_jtfSegundoApellidoActionPerformed

    
    
    //DATOS DE BANCO.
    
    
    
    private void jtfCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodClienteActionPerformed
         jtfCodCliente.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Apellidos
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String CodCli=JOptionPane.showInputDialog("Introduce tu codigo de cliente");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+CodCli);//se hace para comprobar.
        jtfCodCliente.setText(CodCli);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wCodCliente=jtfCodCliente.getText();
       System.out.println(wCodCliente);//para comprobar. // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodClienteActionPerformed

    private void jtfBicBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBicBancoActionPerformed
         jtfBicBanco.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Apellidos
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String BisBn=JOptionPane.showInputDialog("Introduce tus apellidos");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+ BisBn);//se hace para comprobar.
        jtfBicBanco.setText(BisBn);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wBicBanco=jtfBicBanco.getText();
       System.out.println(wBicBanco);//para comprobar. // TODO add your handling code here:
    }//GEN-LAST:event_jtfBicBancoActionPerformed

    private void jtfIbanClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIbanClieActionPerformed
         jtfIbanClie.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Apellidos
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String ibanC=JOptionPane.showInputDialog("Introduce tus apellidos");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+ ibanC);//se hace para comprobar.
        jtfIbanClie.setText(ibanC);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wIbanClie=jtfIbanClie.getText();
       System.out.println(wIbanClie);//para comprobar. // TODO add your handling code here:
    }//GEN-LAST:event_jtfIbanClieActionPerformed

    private void jtfNomBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomBancoActionPerformed
       jtfNomBanco.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Apellidos
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String nomB=JOptionPane.showInputDialog("Introduce tus apellidos");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+nomB);//se hace para comprobar.
        jtfNomBanco.setText(nomB);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wNomBanco=jtfNomBanco.getText();
       System.out.println(wNomBanco);//para comprobar.   // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomBancoActionPerformed

    private void jtfFecCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFecCaducidadActionPerformed
       jtfFecCaducidad.transferFocus();//para poner el foco encima de la casilla corespondiente
        /*al dar intro en la casilla Apellidos
        nos sale una ventana emergente
        donde escribimos el nombre y se manda este nombre a la casilla corespondiente*/
        String fchaCad=JOptionPane.showInputDialog("Introduce tus apellidos");//ventana emergente para introducir los datos.
        System.out.println("Has introducido   "+fchaCad);//se hace para comprobar.
        jtfFecCaducidad.setText(fchaCad);
        
      /*el texto grabado en  textfield vamos a guardar en variable correspondiente.*/   
        wFecCaducidad=jtfFecCaducidad.getText();
       System.out.println(wFecCaducidad);//para comprobar.   // TODO add your handling code here:
    }//GEN-LAST:event_jtfFecCaducidadActionPerformed

    //RAdioBotones MUJER/HOMBRE.
    
    private void jrbHombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbHombreItemStateChanged
        //jrbHombre.setSelected(false);
        if (jrbHombre.isSelected());
            jrbHombre.setSelected(false);
            wHombre=jrbHombre.getText();
    }//GEN-LAST:event_jrbHombreItemStateChanged

    private void jrbMujerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbMujerItemStateChanged
        //jrbMujer.setSelected(false);
        if (jrbMujer.isSelected());
            jrbMujer.setSelected(false);
            wMujer=jrbMujer.getText();
    }//GEN-LAST:event_jrbMujerItemStateChanged

    
    //QUE CARACTERES SE PUEDE INCERTAR A CADA CAMPO.
    
    
    
    
    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
     
    char c=evt.getKeyChar();
     if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ' ))evt.consume();
     else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las letras y espacios");
                System.out.println("Error sintaxico");
            }


    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfPrimeroApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrimeroApellidoKeyTyped
       
    char c=evt.getKeyChar();
     if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ' ))evt.consume(); 
     else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las letras y espacios");
                System.out.println("Error sintaxico");
            }   
    }//GEN-LAST:event_jtfPrimeroApellidoKeyTyped

    private void jtfSegundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSegundoApellidoKeyTyped
        char c=evt.getKeyChar();
     if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ' ))evt.consume(); 
     
     /* else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las letras y espacios");
                System.out.println("Error sintaxico");
            }  */
        
    }//GEN-LAST:event_jtfSegundoApellidoKeyTyped

    private void jtfMunicipioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMunicipioKeyTyped
       char c=evt.getKeyChar();
     if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ' ))evt.consume();
      else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las letras y espacios");
                System.out.println("Error sintaxico");
            }  
        
    }//GEN-LAST:event_jtfMunicipioKeyTyped

    private void jtfProvinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProvinciaKeyTyped
         char c=evt.getKeyChar();
     if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ' ))evt.consume();
      else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las letras y espacios");
                System.out.println("Error sintaxico");
            }  
        
    }//GEN-LAST:event_jtfProvinciaKeyTyped

    private void jtfTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTelefonoKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las cifras");
                System.out.println("Error sintaxico");
            } 
        
    }//GEN-LAST:event_jtfTelefonoKeyTyped

    private void jtfDisPostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDisPostalKeyTyped
      char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las cifras");
                System.out.println("Error sintaxico");
            }
    }//GEN-LAST:event_jtfDisPostalKeyTyped

    private void jtfCorreoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCorreoEKeyTyped
     char c=evt.getKeyChar();
      if((c<'a'||c>'z') && (c<'A'||c>'Z') && (c<'0'||c>'9')&&(c<'@'||c>'@'))evt.consume();
      else{
                JOptionPane.showMessageDialog(null, "Tiene que contener @");
                System.out.println("Error sintaxico");
      }
      
    }//GEN-LAST:event_jtfCorreoEKeyTyped

    private void jtfDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDireccionKeyTyped
     char c=evt.getKeyChar();
      if((c<'a'||c>'z') && (c<'A'||c>'Z') && (c<'0'||c>'9')&&(c<' '||c>' '))evt.consume();
      else{
                JOptionPane.showMessageDialog(null, "Tiene que contener diferentes caracteres");
                System.out.println("Error sintaxico");   
    }//GEN-LAST:event_jtfDireccionKeyTyped

      
    }
    private void jtfFechaNacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFechaNacKeyTyped
       char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las cifras");
                System.out.println("Error sintaxico");
            }
    }//GEN-LAST:event_jtfFechaNacKeyTyped

    private void jtfCodClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodClienteKeyTyped
         char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las cifras");
                System.out.println("Error sintaxico");
            }
    }//GEN-LAST:event_jtfCodClienteKeyTyped

    private void jtfBicBancoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBicBancoKeyTyped
         char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las cifras");
                System.out.println("Error sintaxico");
            }
    }//GEN-LAST:event_jtfBicBancoKeyTyped

    private void jtfIbanClieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIbanClieKeyTyped
        char c=evt.getKeyChar();
      if((c<'a'||c>'z') && (c<'A'||c>'Z') && (c<'0'||c>'9')&&(c<' '||c>' '))evt.consume();
      else{
                JOptionPane.showMessageDialog(null, "Tiene que contener diferentes caracteres");
                System.out.println("Error sintaxico");   
    }   
    }//GEN-LAST:event_jtfIbanClieKeyTyped

    private void jtfNomBancoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomBancoKeyTyped
         char c=evt.getKeyChar();
     if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' ' ))evt.consume();
      else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las letras y espacios");
                System.out.println("Error sintaxico");
            }  
    }//GEN-LAST:event_jtfNomBancoKeyTyped

    private void jtfFecCaducidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFecCaducidadKeyTyped
       char c=evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
        else{
                JOptionPane.showMessageDialog(null, "Solo se puede introducir las cifras");
                System.out.println("Error sintaxico"); 
    }//GEN-LAST:event_jtfFecCaducidadKeyTyped

    }     
    
/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                





}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistroJZ.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistroJZ.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistroJZ.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        





} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_RegistroJZ.class


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Registro_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtCancelBanc;
    private javax.swing.JButton jbtCancelClie;
    private javax.swing.JButton jbtGrabarBanc;
    private javax.swing.JButton jbtGrabarClie;
    private javax.swing.JButton jbtSalirBanco;
    private javax.swing.JButton jbtSalirClie;
    private javax.swing.JLabel jibNombre;
    private javax.swing.JLabel jlbCorreoE;
    private javax.swing.JLabel jlbDPostal;
    private javax.swing.JLabel jlbDirec;
    private javax.swing.JLabel jlbFechaNac;
    private javax.swing.JLabel jlbMunic;
    private javax.swing.JLabel jlbPrimerApellidp;
    private javax.swing.JLabel jlbProv;
    private javax.swing.JLabel jlbSegundoApellido;
    private javax.swing.JLabel jlbTelefono;
    private javax.swing.JPanel jplMujerHombre;
    private javax.swing.JRadioButton jrbHombre;
    private javax.swing.JRadioButton jrbMujer;
    private javax.swing.JPanel jtapDatCliente;
    private javax.swing.JPanel jtapDatCliente1;
    private javax.swing.JPanel jtapDatosBanco;
    private javax.swing.JTextField jtfBicBanco;
    private javax.swing.JTextField jtfCodCliente;
    private javax.swing.JTextField jtfCorreoE;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfDisPostal;
    private javax.swing.JTextField jtfFecCaducidad;
    private javax.swing.JTextField jtfFechaNac;
    private javax.swing.JTextField jtfIbanClie;
    private javax.swing.JTextField jtfMunicipio;
    private javax.swing.JTextField jtfNomBanco;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPrimeroApellido;
    private javax.swing.JTextField jtfProvincia;
    private javax.swing.JTextField jtfSegundoApellido;
    private javax.swing.JTextField jtfTelefono;
    private javax.swing.JTabbedPane jtpDatosBancarios;
    // End of variables declaration//GEN-END:variables
   
    
    
}
