/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda_virtual;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import tienda_virtual.GestionA;

/**
 *
 * @author Trabajo
 */
public class Frm_InforProductos extends javax.swing.JFrame {

    JFileChooser seleccionado = new JFileChooser();
    /*Pruebas*/
    File archivo;
    byte[] bytesImg;
    GestionA gestion = new GestionA();
    /**
     * Creates new form Frm_InicioJZ_1
     */
    public Frm_InforProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloInfo = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jbtVolver = new javax.swing.JButton();
        jbtAñadir = new javax.swing.JButton();
        jbtConfirmar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlblImagen = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtAreaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Principal");
        setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        setForeground(new java.awt.Color(153, 255, 204));
        setLocation(new java.awt.Point(300, 300));

        lblTituloInfo.setAlignment(java.awt.Label.CENTER);
        lblTituloInfo.setFont(new java.awt.Font("Bodoni MT Black", 2, 22)); // NOI18N
        lblTituloInfo.setText("Datos del Producto");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtVolver.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jbtVolver.setText("Volver");
        jbtVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVolverActionPerformed(evt);
            }
        });

        jbtAñadir.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jbtAñadir.setText("Añadir Cesta");
        jbtAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAñadirActionPerformed(evt);
            }
        });

        jbtConfirmar.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jbtConfirmar.setText("Confirmar Compra");
        jbtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jbtVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(88, 88, 88)
                .addComponent(jbtAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addComponent(jbtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbtAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jbtVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jbtConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jlblImagen.setText(" ");
        jScrollPane3.setViewportView(jlblImagen);

        jtxtAreaTexto.setColumns(20);
        jtxtAreaTexto.setRows(5);
        jScrollPane4.setViewportView(jtxtAreaTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAñadirActionPerformed
        // TODO add your handling code here:
        
        //Prubas//
        if(seleccionado.showDialog(this, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION){
            archivo = seleccionado.getSelectedFile();
            if(archivo.canRead()){
                if (archivo.getName().endsWith("txt")){
                   String contenido= gestion.AbrirTexto(archivo);
                   jtxtAreaTexto.setText(contenido);
                }else{
                   if(archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")||archivo.getName().endsWith("gif")){
                       bytesImg = gestion.AbrirImagen(archivo);
                       ImageIcon imagen = new ImageIcon(bytesImg);
                       //jlblImangen= setIconImage(imagen);
                       //jlblImagen = SetIcon(new ImageIcon(imagen).getImage());
                   }else{
                       JOptionPane.showMessageDialog(null, "Selecciones una imagen");
                   } 
                }
                
            }
            
        }
    }//GEN-LAST:event_jbtAñadirActionPerformed

    private void jbtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmarActionPerformed
        // TODO add your handling code here:
        if(seleccionado.showDialog(this, "GUARDAR IMAGEN") == JFileChooser.APPROVE_OPTION){
            archivo = seleccionado.getSelectedFile();
            if(archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")||archivo.getName().endsWith("gif")){
                String respuesta = gestion.GuardarAimagen(archivo, bytesImg);
                if(respuesta != null){
                    JOptionPane.showMessageDialog(null, respuesta);
                }else{
                    JOptionPane.showMessageDialog(null, "Error al guardar imagen");
                }
            }else{
                JOptionPane.showMessageDialog(null, "La imagen se debe guardar en formato imangen");
            }
            
        }
    }//GEN-LAST:event_jbtConfirmarActionPerformed

    private void jbtVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVolverActionPerformed
        // TODO add your handling code here:
        if(seleccionado.showDialog(this, "GUARDAR TEXTO") == JFileChooser.APPROVE_OPTION){
            archivo = seleccionado.getSelectedFile();
            String contenido = jtxtAreaTexto.getText();
            if(archivo.getName().endsWith("txt") ){
                String respuesta = gestion.GuardarTexto(archivo, contenido);
                if(respuesta != null){
                    JOptionPane.showMessageDialog(null, respuesta);
                }else{
                    JOptionPane.showMessageDialog(null, "Error al guardar imagen");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El texto se en formato imangen");
            }
        }    
    }//GEN-LAST:event_jbtVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_InforProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_InforProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_InforProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_InforProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_InforProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtAñadir;
    private javax.swing.JButton jbtConfirmar;
    private javax.swing.JButton jbtVolver;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JTextArea jtxtAreaTexto;
    private java.awt.Label lblTituloInfo;
    // End of variables declaration//GEN-END:variables
}
